//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OtoGaleri
{
    using System;
    using System.Collections.Generic;
    
    public partial class KULLANICI
    {
        public int Kul_ID { get; set; }
        public string Kul_Ad_Soyad { get; set; }
        public string Kul_Mail { get; set; }
        public string Kul_Tel { get; set; }
        public string Kul_Sifre { get; set; }
        public string Kul_Foto { get; set; }
    }
}
