//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OtoGaleri
{
    using System;
    using System.Collections.Generic;
    
    public partial class MUSTERI
    {
        public int Musteri_ID { get; set; }
        public string Musteri_TC { get; set; }
        public string Musteri_Ad_Soyad { get; set; }
        public string Musteri_Mail { get; set; }
        public string Musteri_Tel { get; set; }
        public int Musteri_İl { get; set; }
        public int Musteri_İlçe { get; set; }
        public string Musteri_Adres { get; set; }
        public int Arac_ID { get; set; }
        public string Ehliyet { get; set; }
    
        public virtual ARACLAR ARACLAR { get; set; }
        public virtual ilceler ilceler { get; set; }
        public virtual iller iller { get; set; }
    }
}
