//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OtoGaleri
{
    using System;
    using System.Collections.Generic;
    
    public partial class PERSONEL
    {
        public int Personel_ID { get; set; }
        public string Personel_TC { get; set; }
        public string Personel_Ad_Soyad { get; set; }
        public string Personel_Yas { get; set; }
        public string Personel_Tel { get; set; }
        public string Personel_Mail { get; set; }
        public Nullable<int> Sube_ID { get; set; }
        public string Personel_Foto { get; set; }
    
        public virtual SUBE SUBE { get; set; }
    }
}
