//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OtoGaleri
{
    using System;
    using System.Collections.Generic;
    
    public partial class SUBE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SUBE()
        {
            this.PERSONEL = new HashSet<PERSONEL>();
        }
    
        public int Sube_ID { get; set; }
        public string Sube_Ad { get; set; }
        public string Sorumlı_Kisi { get; set; }
        public string Sube_Tel { get; set; }
        public string Sube_Mail { get; set; }
        public Nullable<int> Sube_il { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PERSONEL> PERSONEL { get; set; }
        public virtual iller iller { get; set; }
    }
}
